runtime: python311
instance_class: F1
service: hercules-api-key
entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker pjecz_hercules_api_key.main:app
env_variables:
  PROJECT_ID: justicia-digital-gob-mx
  SERVICE_PREFIX: pjecz_plataforma_web_api_key
vpc_access_connector:
  name: projects/justicia-digital-gob-mx/locations/us-west2/connectors/cupido
