name: Google Cloud App Engine deploy

on:
  push:
    branches: ["main"]

jobs:
  production-deploy:
    if: github.repository == 'PJECZ/pjecz-hercules-api-key'
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Check out the repository"
        uses: "actions/checkout@v3"

      - name: "Setup Python 3.11"
        uses: "actions/setup-python@v4"
        with:
          python-version: '3.11'

      - name: "Create requirements.txt from pyproject.toml with Poetry"
        run: |
          pip install 'poetry>=2.0.1'
          poetry self add poetry-plugin-export
          poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: "Authenticate"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_KEY }}

      - name: "Deploy"
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: "app.yaml"
          working_directory: "."
          promote: true
