name: Google Cloud App Engine deploy

on:
  push:
    branches: ["main"]

jobs:
  production-deploy:
    if: github.repository == 'PJECZ/pjecz-hercules-api-key'
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Check out the repository"
        uses: "actions/checkout@v3"

      - name: "Setup Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: '3.11'

      - name: "Install Poetry"
        run: pip install poetry

      - name: "Export dependencies to requirements.txt"
        run: poetry export --without-hashes --output requirements.txt

      - name: "Authenticate"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_KEY }}

      - name: "Deploy"
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: "app.yaml"
          working_directory: "."
          promote: true
